# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrendRoadChartsSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # 网络请求
  pod 'Alamofire', '~> 4.8.0'
  # 自动布局
  pod 'SnapKit', '~> 4.0.0'
  # 等待动画
  pod 'NVActivityIndicatorView'
  # hue颜色
  pod 'Hue'
  # json解析
  pod 'SwiftyJSON', '~> 4.2.0'
  # json与model的映射
  pod 'ObjectMapper', '~> 3.4.2'
  # 解析xml
  pod 'SWXMLHash', '~> 4.7.0'
  # 滚动分页展示
  # Pods for TrendRoadChartsSample

  target 'TrendRoadChartsSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrendRoadChartsSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
